/**
 * Parser + merge-logic tests (node:test, no runner deps — `npm test`).
 *
 * The committed fixtures are two real (small) UAR replays; the .expected.json
 * snapshots were generated by the parser at the point where its output was
 * byte-identical to the reference Python pipeline (mpyq + s2protocol) across
 * all replays, and E2E-verified in production. Any diff against them is a
 * regression, not a fixture update — regenerate snapshots only when the
 * output format changes on purpose.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
	parseReplay,
	peekReplay,
	buildPlayersData,
	filetimeToIso,
	type ReplaySighting
} from '../src/lib/server/replay/extract.ts';
import { hx1, hxList, decodeUnlocks } from '../src/lib/server/replay/bank.ts';
import { decideIngest } from '../src/lib/server/replay/ingest.ts';

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(HERE, 'fixtures');

const mosIds = new Set<string>(
	(JSON.parse(readFileSync(join(HERE, '..', 'src', 'lib', 'data', 'mos.json'), 'utf8')) as { id: string }[]).map(
		(m) => m.id
	)
);

function parseFixture(name: string) {
	return parseReplay(`${name}.SC2Replay`, readFileSync(join(FIXTURES, `${name}.SC2Replay`)), mosIds);
}

function expected(name: string) {
	return JSON.parse(readFileSync(join(FIXTURES, `${name}.expected.json`), 'utf8'));
}

test('bank cipher: base-7 integers (values cross-checked in-game)', () => {
	assert.equal(hx1(''), 0);
	assert.equal(hx1('t'), 0);
	assert.equal(hx1('j'), 1);
	assert.equal(hx1('o'), 6);
	assert.equal(hx1('tj'), 7); // least-significant digit first
	assert.equal(hx1('ctotoc'), 48316); // KanaxStratz EN xp on 2026-07-23
	assert.equal(hx1('ccychh'), 58571); // StarTurd EN xp on 2026-07-23
	assert.deepEqual(hxList('j c wh'), [1, 2, 25]); // wh = 4 + 3*7, LSD first
	assert.deepEqual(hxList(''), [0]);
});

test('bank cipher: unlock bit-strings', () => {
	// no bank keys at all -> only the forced camo unlocks, all gear locked
	const empty = decodeUnlocks({});
	assert.deepEqual(empty.camos, [1, 19]);
	assert.deepEqual(empty.sis, []);
	assert.deepEqual(empty.walker, [false, false, false, false, false, false]);
	// bool chars: true set "howfk", false set "cglzmn"
	const gear = decodeUnlocks({ p: 'hcwzkg' });
	assert.deepEqual(gear.walker, [true, false, true, false, true, false]);
	// cluster rockets (walker[5]) grant decal 11
	assert.deepEqual(decodeUnlocks({ p: 'ccccch' }).decals.includes(11), true);
});

test('filetimeToIso: 100ns ticks since 1601', () => {
	assert.equal(filetimeToIso(0), '1601-01-01T00:00:00Z');
	// 2026-07-23T18:08:14Z round-trip via the fixture below
});

test('fixture 20260723-1802: solo game, no bank preload', () => {
	const parsed = parseFixture('20260723-1802');
	assert.deepEqual(parsed, expected('20260723-1802'));
	assert.equal(parsed.title, 'Undead Assault reborn');
	assert.equal(parsed.sightings.length, 0);
	// the one hero died and the recording ends there: the map's game-over
	// condition (every hero down) held when the replay stopped
	assert.equal(parsed.outcome, 'loss');
});

test('fixture 20260723-1808: full bank decode matches snapshot', () => {
	const parsed = parseFixture('20260723-1808');
	assert.deepEqual(parsed, expected('20260723-1808'));
	const s = parsed.sightings[0];
	assert.equal(s.name, 'KanaxStratz');
	assert.equal(s.toon, '2-S2-1-1809580');
	assert.equal(s.xpEn, 48316);
	assert.equal(parsed.playedAt, '2026-07-23T18:08:14Z');
	// left during class selection — no hero was ever born, so the replay
	// carries no evidence either way
	assert.equal(parsed.outcome, null);
});

test('peekReplay agrees with the full parse (cheap dedupe path)', () => {
	const full = parseFixture('20260723-1808');
	const peeked = peekReplay(readFileSync(join(FIXTURES, '20260723-1808.SC2Replay')));
	assert.equal(peeked.playedAt, full.playedAt);
	assert.equal(peeked.title, full.title);
	assert.equal(peeked.lobbyId, full.lobbyId);
	assert.equal(peeked.lobbyId, 3148612723); // lobby-wide m_randomValue
	assert.equal(peeked.durationLoops, full.durationLoops);
	assert.equal(peeked.durationLoops, 408); // ~26s recording
});

test('ingest decisions: lobby identity, replace-if-longer, name suffixing', () => {
	const peeked = { playedAt: '2026-07-23T18:08:14Z', lobbyId: 42, durationLoops: 5000 };

	// new game, minute free -> plain time name
	assert.deepEqual(decideIngest(peeked, null, false), {
		kind: 'insert',
		name: '20260723-1808.SC2Replay'
	});
	// new game, another game already took that minute -> lobby-id suffix
	assert.deepEqual(decideIngest(peeked, null, true), {
		kind: 'insert',
		name: '20260723-1808-42.SC2Replay'
	});
	// same lobby, stored recording is longer or equal -> duplicate
	assert.deepEqual(decideIngest(peeked, { _id: 'x.SC2Replay', durationLoops: 5000 }, false), {
		kind: 'duplicate'
	});
	assert.deepEqual(decideIngest(peeked, { _id: 'x.SC2Replay', durationLoops: 9000 }, false), {
		kind: 'duplicate'
	});
	// same lobby, upload is a longer recording -> replace under the stored name
	assert.deepEqual(decideIngest(peeked, { _id: 'x.SC2Replay', durationLoops: 400 }, false), {
		kind: 'replace',
		name: 'x.SC2Replay'
	});
});

test('canonical name stamp from game time', () => {
	const stamp = '2026-07-23T18:08:14Z'.replace(/[-:]/g, '').slice(0, 13).replace('T', '-');
	assert.equal(stamp, '20260723-1808');
});

function fakeSighting(over: Partial<ReplaySighting>): ReplaySighting {
	return {
		name: 'P',
		clan: '',
		toon: '2-S2-1-1',
		xpEn: 0,
		xpWo: 0,
		xpCo: 0,
		prestige: 0,
		gamesPlayed: 0,
		revives: 0,
		avgGameTime: 0,
		winsByMode: [1, 2],
		camo: 1,
		decal: 0,
		unlocks: decodeUnlocks({}),
		mos: [],
		playedAt: '2026-01-01T00:00:00Z',
		file: 'a.SC2Replay',
		...over
	};
}

function fakeReplay(file: string, playedAt: string, sightings: ReplaySighting[]) {
	return {
		replay: {
			file,
			playedAt,
			title: 'Undead Assault reborn',
			baseBuild: 97563,
			protocolExact: true,
			lobbyId: 42,
			durationLoops: 1000,
			gameLoops: 1000,
			outcome: null,
			mode: null,
			modifiers: [],
			modifiersRead: false,
			mapChecksum: 0,
			sightings
		},
		size: 1000
	};
}

test('buildPlayersData: newest sighting wins, history ordered, career sort', () => {
	const older = fakeSighting({ xpEn: 100, gamesPlayed: 10, playedAt: '2026-01-01T00:00:00Z', file: 'a.SC2Replay' });
	const newer = fakeSighting({ xpEn: 200, gamesPlayed: 11, playedAt: '2026-02-01T00:00:00Z', file: 'b.SC2Replay' });
	const prestiged = fakeSighting({
		toon: '2-S2-1-2',
		name: 'Q',
		xpEn: 50000,
		prestige: 1,
		playedAt: '2026-02-01T00:00:00Z',
		file: 'b.SC2Replay'
	});
	// pass replays out of order on purpose — merge sorts by file name / playedAt
	const data = buildPlayersData([
		fakeReplay('b.SC2Replay', '2026-02-01T00:00:00Z', [newer, prestiged]),
		fakeReplay('a.SC2Replay', '2026-01-01T00:00:00Z', [older])
	]);

	assert.equal(data.replays[0].file, 'a.SC2Replay'); // meta sorted by playedAt
	assert.equal(data.players.length, 2);
	// prestige counts 600k -> Q (650k career) outranks P (200)
	assert.equal(data.players[0].name, 'Q');
	const p = data.players[1] as Record<string, unknown>;
	assert.equal(p.xpEn, 200); // newest wins
	const history = p.history as { file: string; wins: number }[];
	assert.deepEqual(
		history.map((h) => h.file),
		['a.SC2Replay', 'b.SC2Replay'] // oldest first
	);
	assert.equal(history[0].wins, 3); // winsByMode summed
});

test('buildPlayersData: time on record is each game for as long as the player was in it', () => {
	const stayed = fakeSighting({ playedAt: '2026-01-01T00:00:00Z', file: 'a.SC2Replay' });
	const left = fakeSighting({
		toon: '2-S2-1-2',
		name: 'Q',
		playedAt: '2026-01-01T00:00:00Z',
		file: 'a.SC2Replay',
		mos: ['CombatMedic', 'SFAAT'], // re-picked: both classes get the ten seconds
		leftLoop: 160 // ten seconds into a 1000-loop game
	});
	const again = fakeSighting({ playedAt: '2026-02-01T00:00:00Z', file: 'b.SC2Replay' });
	const idler = fakeReplay('b.SC2Replay', '2026-02-01T00:00:00Z', [again]);
	// a recording that ran on past the game: the game's length is what counts
	idler.replay.durationLoops = 100_000;
	idler.replay.gameLoops = 1000;
	const data = buildPlayersData([
		fakeReplay('a.SC2Replay', '2026-01-01T00:00:00Z', [stayed, left]),
		idler
	]);
	const by = Object.fromEntries(data.players.map((p) => [p.toon as string, p]));
	// P: two 1000-loop games at 16 loops/s, each rounded to whole seconds like
	// the boards do (62.5 -> 63); Q: the ten seconds before leaving
	assert.equal(by['2-S2-1-1'].playSeconds, 126);
	assert.equal(by['2-S2-1-2'].playSeconds, 10);
	// the same seconds by class picked, a re-pick game counting in full for both
	assert.deepEqual(by['2-S2-1-2'].classSeconds, { CombatMedic: 10, SFAAT: 10 });
	assert.deepEqual(by['2-S2-1-1'].classSeconds, {});
});

/* The committed golden set cannot cover this: all four of its replays give
   every player exactly one sighting, so there is never a pair to difference
   and "no awards anywhere" is its correct output. These two say what happens
   when a player does appear twice. */

test('buildPlayersData: a game carries what the next bank reveals it gave', () => {
	const unlocks = decodeUnlocks({});
	const older = fakeSighting({
		gamesPlayed: 10,
		playedAt: '2026-01-01T00:00:00Z',
		file: 'a.SC2Replay'
	});
	const newer = fakeSighting({
		gamesPlayed: 11,
		playedAt: '2026-02-01T00:00:00Z',
		file: 'b.SC2Replay',
		unlocks: { ...unlocks, medals: [...unlocks.medals, 3] }
	});
	const data = buildPlayersData([
		fakeReplay('a.SC2Replay', '2026-01-01T00:00:00Z', [older]),
		fakeReplay('b.SC2Replay', '2026-02-01T00:00:00Z', [newer])
	]);

	const history = (data.players[0] as Record<string, unknown>).history as {
		file: string;
		awards?: { type: string; id: number }[];
	}[];
	// credited to the game that was played, not to the one that revealed it
	assert.deepEqual(history[0].awards, [{ type: 'medal', id: 3 }]);
	// and the newest game has no follow-up yet, so it claims nothing
	assert.equal(history[1].awards, undefined);
});

test('buildPlayersData: a game that gave nothing carries no awards key at all', () => {
	// the field is absent rather than empty: history is the one unbounded array
	// on a player, and an empty array on every row of it is paid for on every read
	const older = fakeSighting({ gamesPlayed: 10, playedAt: '2026-01-01T00:00:00Z', file: 'a.SC2Replay' });
	const newer = fakeSighting({ gamesPlayed: 11, playedAt: '2026-02-01T00:00:00Z', file: 'b.SC2Replay' });
	const data = buildPlayersData([
		fakeReplay('a.SC2Replay', '2026-01-01T00:00:00Z', [older]),
		fakeReplay('b.SC2Replay', '2026-02-01T00:00:00Z', [newer])
	]);

	const history = (data.players[0] as Record<string, unknown>).history as Record<string, unknown>[];
	assert.ok(!('awards' in history[0]), 'expected no awards key on a game that gave nothing');
});
