/**
 * Parser + merge-logic tests (node:test, no runner deps — `npm test`).
 *
 * The committed fixtures are two real (small) UAR replays; the .expected.json
 * snapshots were generated by the parser at the point where its output was
 * byte-identical to the reference Python pipeline (mpyq + s2protocol) across
 * all replays, and E2E-verified in production. Any diff against them is a
 * regression, not a fixture update — regenerate snapshots only when the
 * output format changes on purpose.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
	parseReplay,
	peekReplay,
	buildPlayersData,
	filetimeToIso,
	type ReplaySighting
} from '../src/lib/server/replay/extract.ts';
import { hx1, hxList, decodeUnlocks } from '../src/lib/server/replay/bank.ts';

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(HERE, 'fixtures');

const mosIds = new Set<string>(
	(JSON.parse(readFileSync(join(HERE, '..', 'src', 'lib', 'data', 'mos.json'), 'utf8')) as { id: string }[]).map(
		(m) => m.id
	)
);

function parseFixture(name: string) {
	return parseReplay(`${name}.SC2Replay`, readFileSync(join(FIXTURES, `${name}.SC2Replay`)), mosIds);
}

function expected(name: string) {
	return JSON.parse(readFileSync(join(FIXTURES, `${name}.expected.json`), 'utf8'));
}

test('bank cipher: base-7 integers (values cross-checked in-game)', () => {
	assert.equal(hx1(''), 0);
	assert.equal(hx1('t'), 0);
	assert.equal(hx1('j'), 1);
	assert.equal(hx1('o'), 6);
	assert.equal(hx1('tj'), 7); // least-significant digit first
	assert.equal(hx1('ctotoc'), 48316); // KanaxStratz EN xp on 2026-07-23
	assert.equal(hx1('ccychh'), 58571); // StarTurd EN xp on 2026-07-23
	assert.deepEqual(hxList('j c wh'), [1, 2, 25]); // wh = 4 + 3*7, LSD first
	assert.deepEqual(hxList(''), [0]);
});

test('bank cipher: unlock bit-strings', () => {
	// no bank keys at all -> only the forced camo unlocks, all gear locked
	const empty = decodeUnlocks({});
	assert.deepEqual(empty.camos, [1, 19]);
	assert.deepEqual(empty.sis, []);
	assert.deepEqual(empty.walker, [false, false, false, false, false, false]);
	// bool chars: true set "howfk", false set "cglzmn"
	const gear = decodeUnlocks({ p: 'hcwzkg' });
	assert.deepEqual(gear.walker, [true, false, true, false, true, false]);
	// cluster rockets (walker[5]) grant decal 11
	assert.deepEqual(decodeUnlocks({ p: 'ccccch' }).decals.includes(11), true);
});

test('filetimeToIso: 100ns ticks since 1601', () => {
	assert.equal(filetimeToIso(0), '1601-01-01T00:00:00Z');
	// 2026-07-23T18:08:14Z round-trip via the fixture below
});

test('fixture 20260723-1802: solo game, no bank preload', () => {
	const parsed = parseFixture('20260723-1802');
	assert.deepEqual(parsed, expected('20260723-1802'));
	assert.equal(parsed.title, 'Undead Assault reborn');
	assert.equal(parsed.sightings.length, 0);
});

test('fixture 20260723-1808: full bank decode matches snapshot', () => {
	const parsed = parseFixture('20260723-1808');
	assert.deepEqual(parsed, expected('20260723-1808'));
	const s = parsed.sightings[0];
	assert.equal(s.name, 'KanaxStratz');
	assert.equal(s.toon, '2-S2-1-1809580');
	assert.equal(s.xpEn, 48316);
	assert.equal(parsed.playedAt, '2026-07-23T18:08:14Z');
});

test('peekReplay agrees with the full parse (cheap dedupe path)', () => {
	const full = parseFixture('20260723-1808');
	const peeked = peekReplay(readFileSync(join(FIXTURES, '20260723-1808.SC2Replay')));
	assert.equal(peeked.playedAt, full.playedAt);
	assert.equal(peeked.title, full.title);
	assert.equal(peeked.lobbyId, full.lobbyId);
	assert.equal(peeked.lobbyId, 3148612723); // lobby-wide m_randomValue
});

test('canonical name stamp from game time', () => {
	const stamp = '2026-07-23T18:08:14Z'.replace(/[-:]/g, '').slice(0, 13).replace('T', '-');
	assert.equal(stamp, '20260723-1808');
});

function fakeSighting(over: Partial<ReplaySighting>): ReplaySighting {
	return {
		name: 'P',
		clan: '',
		toon: '2-S2-1-1',
		xpEn: 0,
		xpWo: 0,
		xpCo: 0,
		prestige: 0,
		gamesPlayed: 0,
		revives: 0,
		avgGameTime: 0,
		winsByMode: [1, 2],
		camo: 1,
		decal: 0,
		unlocks: decodeUnlocks({}),
		mos: [],
		playedAt: '2026-01-01T00:00:00Z',
		file: 'a.SC2Replay',
		...over
	};
}

function fakeReplay(file: string, playedAt: string, sightings: ReplaySighting[]) {
	return {
		replay: {
			file,
			playedAt,
			title: 'Undead Assault reborn',
			baseBuild: 97563,
			protocolExact: true,
			lobbyId: 42,
			sightings
		},
		size: 1000
	};
}

test('buildPlayersData: newest sighting wins, history ordered, career sort', () => {
	const older = fakeSighting({ xpEn: 100, gamesPlayed: 10, playedAt: '2026-01-01T00:00:00Z', file: 'a.SC2Replay' });
	const newer = fakeSighting({ xpEn: 200, gamesPlayed: 11, playedAt: '2026-02-01T00:00:00Z', file: 'b.SC2Replay' });
	const prestiged = fakeSighting({
		toon: '2-S2-1-2',
		name: 'Q',
		xpEn: 50000,
		prestige: 1,
		playedAt: '2026-02-01T00:00:00Z',
		file: 'b.SC2Replay'
	});
	// pass replays out of order on purpose — merge sorts by file name / playedAt
	const data = buildPlayersData([
		fakeReplay('b.SC2Replay', '2026-02-01T00:00:00Z', [newer, prestiged]),
		fakeReplay('a.SC2Replay', '2026-01-01T00:00:00Z', [older])
	]);

	assert.equal(data.replays[0].file, 'a.SC2Replay'); // meta sorted by playedAt
	assert.equal(data.players.length, 2);
	// prestige counts 600k -> Q (650k career) outranks P (200)
	assert.equal(data.players[0].name, 'Q');
	const p = data.players[1] as Record<string, unknown>;
	assert.equal(p.xpEn, 200); // newest wins
	const history = p.history as { file: string; wins: number }[];
	assert.deepEqual(
		history.map((h) => h.file),
		['a.SC2Replay', 'b.SC2Replay'] // oldest first
	);
	assert.equal(history[0].wins, 3); // winsByMode summed
});
